--- #YAML:1.0
name: Parse-Debian-Packages
version: 0.01
license: perl
distribution_type: module
requires:
  Module::Build: 0.18
  Test::More: 0
recommends: {}
build_requires: {}
conflicts: {}
provides:
  Parse::Debian::Packages:
    file: lib/Parse/Debian/Packages.pm
    version: 0.01
generated_by: Module::Build version 0.21
